version: "3.7"

services:
    database:
        image: postgres
        container_name: products_ms
        restart: always
        ports:
        #PORT 5433 USED FOR PRODUCTS
            - 5433:5432
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - pgdata:/data/postgres
        env_file: .env
volumes:
    pgdata:
        driver: local
